lib/snickr_web/router.ex
defmodule SnickrWeb.Router do
  use SnickrWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SnickrWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SnickrWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create, :show]
    post "/users/search", UserController, :search
    post "/users/invite", UserController, :inviteSearch
    post "/invites/:id", InviteController, :show
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/workspaces", WorkspaceController, only: [:index, :new, :create, :show]
    resources "/channels", ChannelController, only: [:new, :create, :show]
    resources "/invites", InviteController, only: [:index, :show, :create]
    post "/admin_invites", InviteController, :create_admin
    post "/subscription_invites", InviteController, :create_subscription
    post "/invites/:id/accept", InviteController, :accept
    post "/invites/:id/accept_admin", InviteController, :accept_admin
    post "/invites/:id/accept_subscription", InviteController, :accept_subscription
    post "/invites/:id/decline", InviteController, :decline
    post "/invites/:id/decline_admin", InviteController, :decline_admin
    post "/invites/:id/decline_subscription", InviteController, :decline_subscription
    post "/subscriptions", SubscriptionController, :create
    delete "/subscriptions/:user_id/:channel_id", SubscriptionController, :delete
    post "/messages/search", MessageController, :search

    get "/*path", NoRouteController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SnickrWeb do
  #   pipe_through :api
  # end
end

lib/snickr/platform/workspace.ex
defmodule Snickr.Platform.Workspace do
  use Ecto.Schema
  import Ecto.Changeset

  alias Snickr.Platform.Channel
  alias Snickr.Accounts.{AdminInvitation, MembershipInvitation, User}

  schema "workspaces" do
    field :description, :string, null: false
    field :name, :string, null: false
    belongs_to :created_by_user, User
    has_many :channels, Channel

    many_to_many :members, User, join_through: "memberships"
    many_to_many :admins, User, join_through: "admins"

    has_many :membership_invitations, MembershipInvitation, foreign_key: :workspace_id
    has_many :admin_invitations, AdminInvitation, foreign_key: :workspace_id

    timestamps(type: :utc_datetime)
  end

  @doc false
  def changeset(workspace, attrs) do
    workspace
    |> cast(attrs, [:name, :description])
    |> validate_required([:name, :description])
  end

  def create_changeset(workspace, %User{} = created_by_user, attrs) do
    workspace
    |> changeset(attrs)
    |> put_assoc(:created_by_user, created_by_user)
    |> validate_required([:created_by_user])
  end
end

lib/snickr_web/controllers/workspace_controller.ex
defmodule SnickrWeb.WorkspaceController do
  use SnickrWeb, :controller

  alias Snickr.Accounts
  alias Snickr.Platform
  alias Snickr.Platform.Workspace

  plug :authenticate_user

  def new(conn, _attrs) do
    render(conn, "new.html", changeset: Workspace.changeset(%Workspace{}, %{}))
  end

  def create(conn, %{"workspace" => workspace_attrs}) do
    case Platform.create_workspace(conn.assigns.current_user, workspace_attrs) do
      {:ok, workspace} ->
        conn
        |> put_flash(:info, "You have successfully created the #{workspace.name} workspace!")
        |> redirect(to: Routes.workspace_path(conn, :show, workspace.id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def index(conn, _attrs) do
    render(conn, "index.html", workspaces: Platform.list_workspaces(conn.assigns.current_user))
  end

  def show(conn, %{"id" => id}) do
    case Platform.get_workspace_with_member(conn.assigns.current_user, id) do
      nil ->
        conn
        |> put_flash(:error, "Workspace not found")
        |> redirect(to: Routes.workspace_path(conn, :index))

      workspace ->
        render(conn, "show.html",
          workspace: workspace,
          channels:
            Accounts.list_subscribed_to_channels_in_workspace(
              conn.assigns.current_user,
              workspace
            ),
          public_channels: Platform.list_public_channels(workspace)
        )
    end
  end
end

lib/snickr_web/views/workspace_view.ex
defmodule SnickrWeb.WorkspaceView do
  use SnickrWeb, :view

  import SnickrWeb.ChannelView, only: [direct_recipient: 2]

  def sort_channels(c1, c2) do
    precedence = ["public", "private", "direct"]

    Enum.find_index(precedence, fn x -> x == c1.type end) <=
      Enum.find_index(precedence, fn x -> x == c2.type end)
  end
end

lib/snickr_web/templates/workspace/index.html.eex
<h1>Your Workspaces</h1>

<ul>
<%= for w <- @workspaces do %>
  <li><%= link w.name, to: Routes.workspace_path(@conn, :show, w.id) %></li>
<% end %>
</ul>

lib/snickr_web/templates/workspace/new.html.eex
<h1>Create Workspace</h1>

<%= form_for @changeset, Routes.workspace_path(@conn, :create), [as: :workspace], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Something went wrong! Please check the errors below</p>
    </div>
  <% end %>
  <div>
    <%= text_input f, :name, placeholder: "Name" %>
    <%= error_tag f, :name %>
  </div>
  <div>
    <%= text_input f, :description, placeholder: "Description" %>
    <%= error_tag f, :description %>
  </div>
  <%= submit "Create" %>
<% end %>

lib/snickr_web/templates/workspace/show.html.eex
<%= link "< Back", to: Routes.workspace_path(@conn, :index) %>
<h1><%= @workspace.name %></h1>
<p><%= @workspace.description %></p>

<%= if Snickr.Accounts.admin?(@current_user, @workspace) do %>
  <h2>Invite Someone to <%= @workspace.name %></h2>
  <div>
    <input id="invite-user" placeholder="Invite a user">
  </div>
  <ul id="invite-search"></ul>

  <h2>Make Someone Admin to <%= @workspace.name %></h2>
  <div>
    <input id="invite-admin" placeholder="Invite a user">
  </div>
  <ul id="inviteAdmin-search"></ul>
<% end %>

<h2>Your Channels</h2>
<ul>
  <%= for c <- Enum.sort(@channels, &sort_channels/2) do %>
    <li>
      <%= if c.type == "direct" do %>
        <%= link direct_recipient(c, @current_user), to: Routes.channel_path(@conn, :show, c.id) %>
      <% else %>
        <%= link c.name, to: Routes.channel_path(@conn, :show, c.id) %>
      <% end %>
      <span style="font-size: 0.8em"><em><%= c.type %></em></span>
    </li>
  <% end %>
</ul>

<%= link "Create a Channel", to: Routes.channel_path(@conn, :new, workspace_id: @workspace.id) %>

<br>
<br>

<h2>Start a Direct Message</h2>
<div>
  <input id="direct-message" placeholder="Find a user">
</div>
<ul id="search-results"></ul>

<h2>Public Channels</h2>
<ul>
<%= for c <- @public_channels do %>
  <li>
    <%= c.name %>
    <%= if Snickr.Accounts.subscriber?(@current_user, c) do %>
      <button disabled="true">Subscribed</button>
    <% else %>
      <%= form_for Snickr.Accounts.Subscription.changeset(%Snickr.Accounts.Subscription{}, %{}), Routes.subscription_path(@conn, :create), [as: :subscription, style: "display:inline"], fn f -> %>
        <%= hidden_input f, :channel_id, value: c.id %>
        <%= submit "Subscribe" %>
      <% end %>
    <% end %>
  </li>
<% end %>
</ul>

<script>
  const CSRF_TOKEN = <%= raw Poison.encode!(Plug.CSRFProtection.get_csrf_token()) %>
  const workspace_id = Number(/workspaces\/(\d+)$/.exec(window.location.href)[1])

  var dmInput = document.querySelector('#direct-message')
  var searchResultsElement = document.querySelector('#search-results')
  var inviteUser = document.querySelector('#invite-user')
  var inviteSearch = document.querySelector('#invite-search')

  var inviteAdmin = document.querySelector('#invite-admin')
  var inviteAdminSearch = document.querySelector('#inviteAdmin-search')

  // Checks if the user is an admin
  if (inviteAdmin && inviteAdminSearch && inviteUser && inviteSearch) {

    inviteAdmin.addEventListener('keyup', function(event) {
      // Clear the list of results
      inviteAdminSearch.innerHTML = ''

      if (event.currentTarget.value.length > 2) {
        inviteAdminSearch.innerHTML = 'LOADING...'
        var req2 = new XMLHttpRequest()
        req2.open("POST", "/users/invite", true)
        req2.setRequestHeader('Content-Type', 'application/json')
        req2.setRequestHeader('X-CSRF-Token', CSRF_TOKEN)
        req2.send(JSON.stringify({
          term: event.currentTarget.value,
          workspace_id: workspace_id
        }))

        req2.onreadystatechange = function() {
          if (this.readyState == 4) {
            if (this.status == 200) {
              inviteAdminSearch.innerHTML = ''
              JSON.parse(this.responseText).forEach(function(result) {
                renderInviteAdminSearchResult(inviteAdminSearch, result)
              })
            } else {
              inviteAdminSearch.innerHTML = 'FAILED'
            }
          }
        }
      }
    })


    inviteUser.addEventListener('keyup', function(event) {
      // Clear the list of results
      inviteSearch.innerHTML = ''

      if (event.currentTarget.value.length > 2) {
        inviteSearch.innerHTML = 'LOADING...'
        var req2 = new XMLHttpRequest()
        req2.open("POST", "/users/invite", true)
        req2.setRequestHeader('Content-Type', 'application/json')
        req2.setRequestHeader('X-CSRF-Token', CSRF_TOKEN)
        req2.send(JSON.stringify({
          term: event.currentTarget.value,
          workspace_id: workspace_id
        }))

        req2.onreadystatechange = function() {
          if (this.readyState == 4) {
            if (this.status == 200) {
              inviteSearch.innerHTML = ''
              JSON.parse(this.responseText).forEach(function(result) {
                renderInviteSearchResult(inviteSearch, result)
              })
            } else {
              inviteSearch.innerHTML = 'FAILED'
            }
          }
        }
      }
    })

  }


  dmInput.addEventListener('keyup', function(event) {
    // Clear the list of results
    searchResultsElement.innerHTML = ''
    
    if (event.currentTarget.value.length > 2) {
      searchResultsElement.innerHTML = 'LOADING...'
      var req = new XMLHttpRequest()
      req.open("POST", "/users/search", true)
      req.setRequestHeader('Content-Type', 'application/json')
      req.setRequestHeader('X-CSRF-Token', CSRF_TOKEN)
      req.send(JSON.stringify({
        term: event.currentTarget.value,
        workspace_id: workspace_id
      }))

      req.onreadystatechange = function() {
        if (this.readyState == 4) {
          if (this.status == 200) {
            searchResultsElement.innerHTML = ''
            JSON.parse(this.responseText).forEach(function(result) {
              renderSearchResult(searchResultsElement, result)
            })
          } 
          else {
            searchResultsElement.innerHTML = 'FAILED'
          }
        }
      }
    }
  })


  // Escapes untrusted strings
  function esc(str) {
    let div = document.createElement('div')
    div.appendChild(document.createTextNode(str))
    return div.innerHTML
  }

  function renderInviteAdminSearchResult(container, result) {
    let template = document.createElement('div')
    template.innerHTML = `
      ${esc(result.username)}: ${esc(result.full_name)}
      <%= form_for Snickr.Accounts.AdminInvitation.changeset(%Snickr.Accounts.AdminInvitation{}, %{}), Routes.invite_path(@conn, :create_admin), [as: :invite], fn f -> %>
        <%= hidden_input f, :status, value: "pending" %>
        <%= hidden_input f, :user_id %>
        <%= hidden_input f, :workspace_id, value: @workspace.id %>
        <%= submit "Send Invite" %>
      <% end %>
    `
    template.querySelector('#invite_user_id').setAttribute('value', result.id)
    container.appendChild(template)
  }

  function renderInviteSearchResult(container, result) {
    let template = document.createElement('div')
    // The changeset I'm creating and passing in isn't used, it's just needed by the form_for method to run properly - if we implemented more robust error handling, we could use a changeset there. [as: :invite] collects all of the attributes of the form into an "invites" map, which the create action in your controller looks for
    template.innerHTML = `
      ${esc(result.username)}: ${esc(result.full_name)}
      <%= form_for Snickr.Accounts.MembershipInvitation.changeset(%Snickr.Accounts.MembershipInvitation{}, %{}), Routes.invite_path(@conn, :create), [as: :invite], fn f -> %>
        <%= hidden_input f, :status, value: "pending" %>
        <%= hidden_input f, :user_id %>
        <%= hidden_input f, :workspace_id, value: @workspace.id %>
        <%= submit "Send Invite" %>
      <% end %>
    `
    // The name of the form is invite, which is automatically used as a prefix for the id of each input in the form
    template.querySelector('#invite_user_id').setAttribute('value', result.id)
    container.appendChild(template)
  }

  function renderSearchResult(container, result) {
    let template = document.createElement('div')
    template.innerHTML = `
      ${esc(result.username)}: ${esc(result.full_name)}
      <%= form_for Snickr.Platform.Channel.changeset(%Snickr.Platform.Channel{}, %{}), Routes.channel_path(@conn, :create, workspace_id: @workspace.id), [as: :channel], fn f -> %>
        <%= hidden_input f, :type, value: "direct" %>
        <%= hidden_input f, :to_user_id %>
        <%= hidden_input f, :workspace_id, value: @workspace.id %>
        <%= submit "Send Message" %>
      <% end %>
    `
    template.querySelector('#channel_to_user_id').setAttribute('value', result.id)
    container.appendChild(template)
  }
</script>